name: granite_example
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_gpu:
    sdk: flutter

  granite:
    path: ..

  http: ^1.4.0
  # flutter_scene: ^0.9.2-0
  flutter_scene:
    path: ../../flutter_scene
  vector_math: ^2.2.0
  latlong2: ^0.9.1


dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
