name: granite_example
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_gpu:
    sdk: flutter

  granite:
    path: ..

  http: ^1.4.0
  # flutter_scene: ^0.9.2-0
  flutter_scene:
    path: ../../flutter_scene
  vector_math: ^2.2.0
  latlong2: ^0.9.1

  native_assets_cli: ^0.13.0
  flutter_gpu_shaders: ^0.3.0

  objective_c: ^8.1.0
  ffi: ^2.1.4


dev_dependencies:
  flutter_lints: ^6.0.0
  ffigen: ^19.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - build/shaderbundles/
