name: granite
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_gpu:
    sdk: flutter

  # common
  collection: ^1.19.1
  # flutter_scene: ^0.9.2-0
  flutter_scene:
    path: ../flutter_scene
  equatable: ^2.0.7
  vector_math: ^2.2.0
  dart_earcut: ^1.2.0
  latlong2: ^0.9.1
  http: ^1.4.0

  # spec
  intl: ^0.20.2

  # vector_tile
  fixnum: ^1.1.1
  protobuf: ^4.1.1

  # ffi or other native tooling
  flutter_gpu_shaders: ^0.3.0
  flat_buffers: ^23.5.26

dev_dependencies:
  analyzer: ^8.0.0
  flutter_lints: ^6.0.0
